### ISSUE TITLE
regexp error - unescaped hyphen in capnames()

### ISSUE THREAD

**Issue by sceox** [volundmush/mushcode#1]
There is a regex error showing up in +help and related systems. 

 `#-1 REGEXP ERROR: invalid range in character class`

It traces back to an unescaped `-` in global function capnames. Patch:

`&GFN`CAPNAMES u(gfo)=regeditall(lcstr(%0),(?<=\[_/\\-\\s\]|^)(\[a-z\]),capstr($1))`

**Comment by volundmush** [comment]
God, how did I miss this issue?

Fixed. Thanks.
