### ISSUE TITLE
Not Quite Sure if this is the Place BUT

### ISSUE THREAD

**Issue by RockyCoon** [volundmush/mushcode#4]
How to integrate AnomalyJobs with your Codesuite? I know there's a patch, but... there's not any real help on how it integrates, and quoting it into my MUSH doesn't make it work. (I get a lot of 'I can't see that here', etc.)

Am I doing something wrong or? is there some more steps I need?

**Comment by RockyCoon** [comment]
Alright. I got the patch to 'work' by installing it as the #1 God Bit. I feel as if that's a temp workaround at best, unless that's the intended installation method?

**Comment by RockyCoon** [comment]
I would also like to add, that- I was using the CodeWiz bit as I have for everything else since database start- for both the AnonJobs installation and the patch and all the codesuite installation.

**Comment by sceox** [comment]
Could you turn on debug and try again? That should show what's going wrong.

If you get many "I can't see that here" it is probably from `u(job)` function not finding the Job Global Object. Is your codewiz player parented to the Code Object Index? What is output of `think name(parent(me))`? Also `think u(job)` and `think locate(config(master_room),Job Global Object <JGO>,TXxi)`?

**Comment by volundmush** [comment]
I did notice there is a problem where using u(job) can conflict if you're
using the staff position, which uses the &job attribute (a stupid oversight
on my part.) The temporary solution is to clear your own &job attribute
when trying to use u(job) to set attributes.

This was really stupid of me. Need to see if I'm still using it that way.

**Comment by volundmush** [comment]
Well I should have closed this one a while ago. Sorry guys! Welcome to 2.0.
