### ISSUE TITLE
Code Names are Mismatched

### ISSUE THREAD

**Issue by ccubed** [volundmush/mushcode#6]
So, it seems like many things aren't matching up.

Your startup for one called `Startup`Extra`, this code doesn't exist in CORE 02. You also never call the startup's on the MCO. Is that intentional?
- https://github.com/volundmush/mushcode/blob/master/CORE%2002%20-%20Codewiz%20Setup.txt#L6

Your code in +gameconfig calls `INC`GETSWITCH`, there is no `INC`GETSWITCH`. There is an `INC`GET` which I assume is what it should be.
- https://github.com/volundmush/mushcode/blob/master/CORE%2003%20-%20Game%20Configuration%20System%20-%20GCS.txt#L29

Your code for the player configuartion system (+config) calls getswitch also, but actually there isn't even a `INC`GET`. Also not an `INC`GETSWITCH`. I think some things got removed from the code on github?
- https://github.com/volundmush/mushcode/blob/master/CORE%2004%20-%20Player%20Configuration%20System%20-%20PCS.txt#L12

As it is nothing works on a fresh install.

**Comment by volundmush** [comment]
Q) STARTUP`EXTRA
A) This attribute exists for you to put whatever you want in it. A few of the games I manage use STARTUP`EXTRA. By default the attribute is empty, so it does nothing. I should add a @@ comment in there about that.

Q) @attach %!/INC`GETSWITCH=%1;
A) INC`GETSWITCH is located on the Master Code Object. All of the code objects like Game Configuration System and Player Configuration System should be automatically @parent linked to the Master Code Object by their install scripts.

Everything is indeed working on the five or so games I'm supporting! If you're having trouble, give me some connect info and I'll see if I can figure out what's going on.

**Comment by ccubed** [comment]
Okay, I don't want to send the details over here, so emailing you.

**Comment by volundmush** [comment]
Gonna consider this one fixed for now. :)
